version: '3'

services:
    node:
        build:
            context: .
            dockerfile: nodejs.dockerfile
        container_name: node
        ports:
            - 80:8080
        volumes:
            - ./nodeserver:/home/node/app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge